apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: efk-logging
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: es-data
        image: elasticsearch:5.2.2
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        args:
          - -Ecluster.name=k8s-es
          - -Enode.master=false
          - -Enode.data=true
          - -Ehttp.enabled=false
          - -Enetwork.host=_site_
          - -Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        #resources:
        #  limits:
        #    memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        cinder:
          volumeID: ce58287f-13b6-40d3-907e-09f562a48330
          type: ext4
