apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-1
  labels:
    type: es-data-pv
spec:
  #persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: ext4
    volumeID: ce58287f-13b6-40d3-907e-09f562a48330 
